new <- c(
  ".mc_assign_states",
  ".mc_fit",
  ".mc_sim",
  "MeteorologyInterpolationData",
  "MeteorologyUncorrectedData",
  "SpatialGridMeteorology",
  "SpatialGridTopography",
  "SpatialPixelsMeteorology",
  "SpatialPixelsTopography",
  "SpatialPointsMeteorology",
  "SpatialPointsTopography",
  "add_topo",
  "averagearea",
  "complete_meteo",
  "correction_series",
  "correctionpoint",
  "correctionpoints",
  "correctionpoints.errors",
  "create_meteo_interpolator",
  "defaultCorrectionParams",
  "defaultGenerationParams",
  "defaultInterpolationParams",
  "downloadAEMETcurrentday",
  "downloadAEMEThistorical",
  "downloadAEMETstationlist",
  "downloadMETEOCLIMATICcurrentday",
  "downloadMETEOCLIMATICstationlist",
  "downloadMGcurrentday",
  "downloadMGhistorical",
  "downloadMGstationlist",
  "downloadSMCcurrentday",
  "downloadSMChistorical",
  "downloadSMCstationlist",
  "extractNetCDF",
  "extractdates",
  "extractgridindex",
  "extractgridpoints",
  "extractvars",
  "get_interpolation_params",
  "humidity_dewtemperature2relative",
  "humidity_relative2dewtemperature",
  "humidity_relative2specific",
  "humidity_specific2relative",
  "interpolate_data",
  "interpolation.calibration",
  "interpolation.calibration.fmax",
  "interpolation.coverage",
  "interpolation.cv",
  "interpolation_cross_validation",
  "interpolation_dewtemperature",
  "interpolation_precipitation",
  "interpolation_temperature",
  "interpolation_wind",
  "interpolationgrid",
  "interpolationpixels",
  "interpolationpoints",
  "interpolator_calibration",
  "mergegrids",
  "mergepoints",
  "meteocomplete",
  "meteoplot",
  "meteospain2meteoland",
  "penman",
  "penmanmonteith",
  "precipitation_concentration",
  "precipitation_rainfallErosivity",
  "radiation_dateStringToJulianDays",
  "radiation_daylength",
  "radiation_daylengthseconds",
  "radiation_directDiffuseDay",
  "radiation_directDiffuseInstant",
  "radiation_julianDay",
  "radiation_netRadiation",
  "radiation_outgoingLongwaveRadiation",
  "radiation_potentialRadiation",
  "radiation_skyLongwaveRadiation",
  "radiation_solarConstant",
  "radiation_solarDeclination",
  "radiation_solarElevation",
  "radiation_solarRadiation",
  "radiation_sunRiseSet",
  "readNetCDFdates",
  "readNetCDFgridtopology",
  "readNetCDFpoints",
  "readNetCDFproj4string",
  "readWindNinjaWindFields",
  "read_interpolator",
  "readmeteorologygrid",
  "readmeteorologygridpoints",
  "readmeteorologypixels",
  "readmeteorologypoint",
  "readmeteorologypointfiles",
  "readmeteorologypoints",
  "reshapemeteospain",
  "reshapeweathercan",
  "reshapeworldmet",
  "set_interpolation_params",
  "summarygrid",
  "summaryinterpolationdata",
  "summarypixels",
  "summarypoint",
  "summarypoints",
  "utils_airDensity",
  "utils_atmosphericPressure",
  "utils_averageDailyVP",
  "utils_averageDaylightTemperature",
  "utils_latentHeatVaporisation",
  "utils_latentHeatVaporisationMol",
  "utils_psychrometricConstant",
  "utils_saturationVP",
  "utils_saturationVaporPressureCurveSlope",
  "weathergeneration",
  "with_meteo",
  "write_interpolator",
  "writeemptymeteorologygrid",
  "writemeteorologygrid",
  "writemeteorologygridpixel",
  "writemeteorologypixels",
  "writemeteorologypoint",
  "writemeteorologypointfiles",
  "writemeteorologypoints"
)

old <- c(
  "averagearea",
  "correctionpoint", "correctionpoints", "correctionpoints.errors", 
  "correction_series",
  "defaultCorrectionParams", "defaultGenerationParams", "defaultInterpolationParams",
  "downloadMGstationlist", "downloadMGcurrentday", "downloadMGhistorical",
  "downloadSMCstationlist","downloadSMCcurrentday", "downloadSMChistorical",
  "downloadAEMETcurrentday","downloadAEMEThistorical", "downloadAEMETstationlist",
  "downloadMETEOCLIMATICcurrentday", "downloadMETEOCLIMATICstationlist",
  "extractgridindex",
  "extractgridpoints", "extractNetCDF",
  "extractdates", "extractvars",
  "humidity_relative2specific", "humidity_specific2relative", "humidity_dewtemperature2relative", "humidity_relative2dewtemperature",
  "interpolation_dewtemperature", "interpolation_precipitation", "interpolation_temperature", "interpolation_wind",
  "interpolationpoints", "interpolationgrid", "interpolationpixels",
  "interpolation.calibration", "interpolation.calibration.fmax", "interpolation.coverage", "interpolation.cv",
  "mergegrids", "mergepoints",
  "meteocomplete", "meteoplot", "MeteorologyUncorrectedData", "MeteorologyInterpolationData",
  "penman", "penmanmonteith", 
  "precipitation_concentration", "precipitation_rainfallErosivity",
  "plot.interpolation.cv",
  "radiation_julianDay", "radiation_solarDeclination", "radiation_solarConstant", "radiation_daylength",
  "radiation_dateStringToJulianDays", "radiation_sunRiseSet", "radiation_daylengthseconds",
  "radiation_potentialRadiation", "radiation_solarElevation", "radiation_solarRadiation", 
  "radiation_directDiffuseInstant", "radiation_directDiffuseDay", "radiation_skyLongwaveRadiation",
  "radiation_outgoingLongwaveRadiation","radiation_netRadiation",
  "readNetCDFpoints","readNetCDFdates", "readNetCDFgridtopology", "readNetCDFproj4string",
  "readmeteorologygridpoints",
  "readmeteorologygrid", "readmeteorologypixels",
  "readmeteorologypoint","readmeteorologypoints","readmeteorologypointfiles", 
  "readWindNinjaWindFields",
  "reshapemeteospain", "reshapeweathercan", "reshapeworldmet", 
  "SpatialPointsTopography", "SpatialGridTopography", "SpatialPixelsTopography", 
  "SpatialGridMeteorology", "SpatialPointsMeteorology", "SpatialPixelsMeteorology",
  "subsample","summary.interpolation.cv", 
  "summarypixels", "summarygrid", "summarypoint", "summarypoints", "summaryinterpolationdata",
  "utils_saturationVP", "utils_averageDailyVP", "utils_atmosphericPressure",
  "utils_airDensity", "utils_averageDaylightTemperature", "utils_latentHeatVaporisation",
  "utils_latentHeatVaporisationMol","utils_psychrometricConstant",
  "utils_saturationVaporPressureCurveSlope",
  "weathergeneration",
  "writemeteorologypixels", "writeemptymeteorologygrid", "writemeteorologygrid", "writemeteorologygridpixel",
  "writemeteorologypoint", "writemeteorologypoints", "writemeteorologypointfiles"
)

all(old %in% new)
nope_index <- which(!old %in% new)
old[nope_index]
new_index <- which(!new %in% old)
new[new_index]
