// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/meteoland.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// temporalSmoothing
NumericMatrix temporalSmoothing(NumericMatrix input, int numDays, bool prec);
RcppExport SEXP meteoland_temporalSmoothing(SEXP inputSEXP, SEXP numDaysSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type numDays(numDaysSEXP);
    Rcpp::traits::input_parameter< bool >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(temporalSmoothing(input, numDays, prec));
    return rcpp_result_gen;
END_RCPP
}
// slope
NumericVector slope(NumericVector data, int nrows, int ncols, double cellWidth, double cellHeight);
RcppExport SEXP meteoland_slope(SEXP dataSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP cellWidthSEXP, SEXP cellHeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< double >::type cellWidth(cellWidthSEXP);
    Rcpp::traits::input_parameter< double >::type cellHeight(cellHeightSEXP);
    rcpp_result_gen = Rcpp::wrap(slope(data, nrows, ncols, cellWidth, cellHeight));
    return rcpp_result_gen;
END_RCPP
}
// aspect
NumericVector aspect(NumericVector data, int nrows, int ncols, double cellWidth, double cellHeight);
RcppExport SEXP meteoland_aspect(SEXP dataSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP cellWidthSEXP, SEXP cellHeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< double >::type cellWidth(cellWidthSEXP);
    Rcpp::traits::input_parameter< double >::type cellHeight(cellHeightSEXP);
    rcpp_result_gen = Rcpp::wrap(aspect(data, nrows, ncols, cellWidth, cellHeight));
    return rcpp_result_gen;
END_RCPP
}
// dailyEquilibriumPET
NumericVector dailyEquilibriumPET(NumericVector Temp, NumericVector Rn);
RcppExport SEXP meteoland_dailyEquilibriumPET(SEXP TempSEXP, SEXP RnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Temp(TempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rn(RnSEXP);
    rcpp_result_gen = Rcpp::wrap(dailyEquilibriumPET(Temp, Rn));
    return rcpp_result_gen;
END_RCPP
}
// PenmanPETPointSeries
NumericVector PenmanPETPointSeries(double latrad, double elevation, double slorad, double asprad, IntegerVector J, NumericVector Tmin, NumericVector Tmax, NumericVector RHmin, NumericVector RHmax, NumericVector R_s, NumericVector u, double z, double z0, double alpha, String windfun);
RcppExport SEXP meteoland_PenmanPETPointSeries(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP R_sSEXP, SEXP uSEXP, SEXP zSEXP, SEXP z0SEXP, SEXP alphaSEXP, SEXP windfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type J(JSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RHmin(RHminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RHmax(RHmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R_s(R_sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< String >::type windfun(windfunSEXP);
    rcpp_result_gen = Rcpp::wrap(PenmanPETPointSeries(latrad, elevation, slorad, asprad, J, Tmin, Tmax, RHmin, RHmax, R_s, u, z, z0, alpha, windfun));
    return rcpp_result_gen;
END_RCPP
}
// PenmanMonteithPETPointSeries
NumericVector PenmanMonteithPETPointSeries(double rc, double elevation, NumericVector Tmin, NumericVector Tmax, NumericVector RHmin, NumericVector RHmax, NumericVector Rn, NumericVector u);
RcppExport SEXP meteoland_PenmanMonteithPETPointSeries(SEXP rcSEXP, SEXP elevationSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP RnSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rc(rcSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RHmin(RHminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RHmax(RHmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(PenmanMonteithPETPointSeries(rc, elevation, Tmin, Tmax, RHmin, RHmax, Rn, u));
    return rcpp_result_gen;
END_RCPP
}
// PenmanPETPointsDay
NumericVector PenmanPETPointsDay(NumericVector latrad, NumericVector elevation, NumericVector slorad, NumericVector asprad, int J, NumericVector Tmin, NumericVector Tmax, NumericVector RHmin, NumericVector RHmax, NumericVector R_s, NumericVector u, double z, double z0, double alpha, String windfun);
RcppExport SEXP meteoland_PenmanPETPointsDay(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP R_sSEXP, SEXP uSEXP, SEXP zSEXP, SEXP z0SEXP, SEXP alphaSEXP, SEXP windfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RHmin(RHminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RHmax(RHmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R_s(R_sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< String >::type windfun(windfunSEXP);
    rcpp_result_gen = Rcpp::wrap(PenmanPETPointsDay(latrad, elevation, slorad, asprad, J, Tmin, Tmax, RHmin, RHmax, R_s, u, z, z0, alpha, windfun));
    return rcpp_result_gen;
END_RCPP
}
// interpolatePrecipitationSeriesPoints
NumericMatrix interpolatePrecipitationSeriesPoints(NumericVector Xp, NumericVector Yp, NumericVector Zp, NumericVector X, NumericVector Y, NumericVector Z, NumericMatrix P, NumericMatrix Psmooth, double iniRp, double alpha_event, double alpha_amount, int N_event, int N_amount, int iterations, double popcrit, double fmax);
RcppExport SEXP meteoland_interpolatePrecipitationSeriesPoints(SEXP XpSEXP, SEXP YpSEXP, SEXP ZpSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP PSEXP, SEXP PsmoothSEXP, SEXP iniRpSEXP, SEXP alpha_eventSEXP, SEXP alpha_amountSEXP, SEXP N_eventSEXP, SEXP N_amountSEXP, SEXP iterationsSEXP, SEXP popcritSEXP, SEXP fmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zp(ZpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Psmooth(PsmoothSEXP);
    Rcpp::traits::input_parameter< double >::type iniRp(iniRpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_event(alpha_eventSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_amount(alpha_amountSEXP);
    Rcpp::traits::input_parameter< int >::type N_event(N_eventSEXP);
    Rcpp::traits::input_parameter< int >::type N_amount(N_amountSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type popcrit(popcritSEXP);
    Rcpp::traits::input_parameter< double >::type fmax(fmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolatePrecipitationSeriesPoints(Xp, Yp, Zp, X, Y, Z, P, Psmooth, iniRp, alpha_event, alpha_amount, N_event, N_amount, iterations, popcrit, fmax));
    return rcpp_result_gen;
END_RCPP
}
// interpolatePrecipitationEventSeriesPoints
NumericMatrix interpolatePrecipitationEventSeriesPoints(NumericVector Xp, NumericVector Yp, NumericVector Zp, NumericVector X, NumericVector Y, NumericVector Z, NumericMatrix Pevent, double iniRp, double alpha, int N, int iterations, double popcrit);
RcppExport SEXP meteoland_interpolatePrecipitationEventSeriesPoints(SEXP XpSEXP, SEXP YpSEXP, SEXP ZpSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP PeventSEXP, SEXP iniRpSEXP, SEXP alphaSEXP, SEXP NSEXP, SEXP iterationsSEXP, SEXP popcritSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zp(ZpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pevent(PeventSEXP);
    Rcpp::traits::input_parameter< double >::type iniRp(iniRpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type popcrit(popcritSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolatePrecipitationEventSeriesPoints(Xp, Yp, Zp, X, Y, Z, Pevent, iniRp, alpha, N, iterations, popcrit));
    return rcpp_result_gen;
END_RCPP
}
// pseudoRainfall
NumericVector pseudoRainfall(NumericVector RainM, NumericVector daysMonthAll, double shape, double scale, int firstMonth);
RcppExport SEXP meteoland_pseudoRainfall(SEXP RainMSEXP, SEXP daysMonthAllSEXP, SEXP shapeSEXP, SEXP scaleSEXP, SEXP firstMonthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type RainM(RainMSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type daysMonthAll(daysMonthAllSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type firstMonth(firstMonthSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudoRainfall(RainM, daysMonthAll, shape, scale, firstMonth));
    return rcpp_result_gen;
END_RCPP
}
// julianDay
int julianDay(int year, int month, int day);
static SEXP meteoland_julianDay_try(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    Rcpp::traits::input_parameter< int >::type month(monthSEXP);
    Rcpp::traits::input_parameter< int >::type day(daySEXP);
    rcpp_result_gen = Rcpp::wrap(julianDay(year, month, day));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_julianDay(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_julianDay_try(yearSEXP, monthSEXP, daySEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dateStringToJulianDays
IntegerVector dateStringToJulianDays(CharacterVector dateStrings);
static SEXP meteoland_dateStringToJulianDays_try(SEXP dateStringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dateStrings(dateStringsSEXP);
    rcpp_result_gen = Rcpp::wrap(dateStringToJulianDays(dateStrings));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_dateStringToJulianDays(SEXP dateStringsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_dateStringToJulianDays_try(dateStringsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// solarDeclination
double solarDeclination(int J);
static SEXP meteoland_solarDeclination_try(SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(solarDeclination(J));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_solarDeclination(SEXP JSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_solarDeclination_try(JSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// solarConstant
double solarConstant(int J);
static SEXP meteoland_solarConstant_try(SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(solarConstant(J));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_solarConstant(SEXP JSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_solarConstant_try(JSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sunRiseSet
NumericVector sunRiseSet(double latrad, double slorad, double asprad, double delta);
static SEXP meteoland_sunRiseSet_try(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(sunRiseSet(latrad, slorad, asprad, delta));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_sunRiseSet(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_sunRiseSet_try(latradSEXP, sloradSEXP, aspradSEXP, deltaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// solarElevation
double solarElevation(double latrad, double delta, double hrad);
static SEXP meteoland_solarElevation_try(SEXP latradSEXP, SEXP deltaSEXP, SEXP hradSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type hrad(hradSEXP);
    rcpp_result_gen = Rcpp::wrap(solarElevation(latrad, delta, hrad));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_solarElevation(SEXP latradSEXP, SEXP deltaSEXP, SEXP hradSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_solarElevation_try(latradSEXP, deltaSEXP, hradSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// daylength
double daylength(double latrad, double slorad, double asprad, double delta);
static SEXP meteoland_daylength_try(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(daylength(latrad, slorad, asprad, delta));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_daylength(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_daylength_try(latradSEXP, sloradSEXP, aspradSEXP, deltaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// daylengthseconds
double daylengthseconds(double latrad, double slorad, double asprad, double delta);
static SEXP meteoland_daylengthseconds_try(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(daylengthseconds(latrad, slorad, asprad, delta));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_daylengthseconds(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_daylengthseconds_try(latradSEXP, sloradSEXP, aspradSEXP, deltaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RpotDay
double RpotDay(double solarConstant, double latrad, double slorad, double asprad, double delta);
static SEXP meteoland_RpotDay_try(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type solarConstant(solarConstantSEXP);
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(RpotDay(solarConstant, latrad, slorad, asprad, delta));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_RpotDay(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_RpotDay_try(solarConstantSEXP, latradSEXP, sloradSEXP, aspradSEXP, deltaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RDay
double RDay(double solarConstant, double latrad, double elevation, double slorad, double asprad, double delta, double diffTemp, double diffTempMonth, double vpa, double precipitation);
static SEXP meteoland_RDay_try(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP diffTempSEXP, SEXP diffTempMonthSEXP, SEXP vpaSEXP, SEXP precipitationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type solarConstant(solarConstantSEXP);
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type diffTemp(diffTempSEXP);
    Rcpp::traits::input_parameter< double >::type diffTempMonth(diffTempMonthSEXP);
    Rcpp::traits::input_parameter< double >::type vpa(vpaSEXP);
    Rcpp::traits::input_parameter< double >::type precipitation(precipitationSEXP);
    rcpp_result_gen = Rcpp::wrap(RDay(solarConstant, latrad, elevation, slorad, asprad, delta, diffTemp, diffTempMonth, vpa, precipitation));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_RDay(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP diffTempSEXP, SEXP diffTempMonthSEXP, SEXP vpaSEXP, SEXP precipitationSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_RDay_try(solarConstantSEXP, latradSEXP, elevationSEXP, sloradSEXP, aspradSEXP, deltaSEXP, diffTempSEXP, diffTempMonthSEXP, vpaSEXP, precipitationSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// directDiffuseInstant
NumericVector directDiffuseInstant(double solarConstant, double latrad, double slorad, double asprad, double delta, double hrad, double R_p, double R_s, bool clearday);
static SEXP meteoland_directDiffuseInstant_try(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP hradSEXP, SEXP R_pSEXP, SEXP R_sSEXP, SEXP cleardaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type solarConstant(solarConstantSEXP);
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type hrad(hradSEXP);
    Rcpp::traits::input_parameter< double >::type R_p(R_pSEXP);
    Rcpp::traits::input_parameter< double >::type R_s(R_sSEXP);
    Rcpp::traits::input_parameter< bool >::type clearday(cleardaySEXP);
    rcpp_result_gen = Rcpp::wrap(directDiffuseInstant(solarConstant, latrad, slorad, asprad, delta, hrad, R_p, R_s, clearday));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_directDiffuseInstant(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP hradSEXP, SEXP R_pSEXP, SEXP R_sSEXP, SEXP cleardaySEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_directDiffuseInstant_try(solarConstantSEXP, latradSEXP, sloradSEXP, aspradSEXP, deltaSEXP, hradSEXP, R_pSEXP, R_sSEXP, cleardaySEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// directDiffuseDay
DataFrame directDiffuseDay(double solarConstant, double latrad, double slorad, double asprad, double delta, double R_s, bool clearday, int nsteps);
static SEXP meteoland_directDiffuseDay_try(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP R_sSEXP, SEXP cleardaySEXP, SEXP nstepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type solarConstant(solarConstantSEXP);
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type R_s(R_sSEXP);
    Rcpp::traits::input_parameter< bool >::type clearday(cleardaySEXP);
    Rcpp::traits::input_parameter< int >::type nsteps(nstepsSEXP);
    rcpp_result_gen = Rcpp::wrap(directDiffuseDay(solarConstant, latrad, slorad, asprad, delta, R_s, clearday, nsteps));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_directDiffuseDay(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP R_sSEXP, SEXP cleardaySEXP, SEXP nstepsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_directDiffuseDay_try(solarConstantSEXP, latradSEXP, sloradSEXP, aspradSEXP, deltaSEXP, R_sSEXP, cleardaySEXP, nstepsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// outgoingLongwaveRadiation
double outgoingLongwaveRadiation(double solarConstant, double latrad, double elevation, double slorad, double asprad, double delta, double vpa, double tmin, double tmax, double R_s);
static SEXP meteoland_outgoingLongwaveRadiation_try(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP vpaSEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP R_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type solarConstant(solarConstantSEXP);
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type vpa(vpaSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type R_s(R_sSEXP);
    rcpp_result_gen = Rcpp::wrap(outgoingLongwaveRadiation(solarConstant, latrad, elevation, slorad, asprad, delta, vpa, tmin, tmax, R_s));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_outgoingLongwaveRadiation(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP vpaSEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP R_sSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_outgoingLongwaveRadiation_try(solarConstantSEXP, latradSEXP, elevationSEXP, sloradSEXP, aspradSEXP, deltaSEXP, vpaSEXP, tminSEXP, tmaxSEXP, R_sSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// netRadiation
double netRadiation(double solarConstant, double latrad, double elevation, double slorad, double asprad, double delta, double vpa, double tmin, double tmax, double R_s, double alpha);
static SEXP meteoland_netRadiation_try(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP vpaSEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP R_sSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type solarConstant(solarConstantSEXP);
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type vpa(vpaSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type R_s(R_sSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(netRadiation(solarConstant, latrad, elevation, slorad, asprad, delta, vpa, tmin, tmax, R_s, alpha));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_netRadiation(SEXP solarConstantSEXP, SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP deltaSEXP, SEXP vpaSEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP R_sSEXP, SEXP alphaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_netRadiation_try(solarConstantSEXP, latradSEXP, elevationSEXP, sloradSEXP, aspradSEXP, deltaSEXP, vpaSEXP, tminSEXP, tmaxSEXP, R_sSEXP, alphaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// potentialRadiationSeries
NumericVector potentialRadiationSeries(double latrad, double slorad, double asprad, NumericVector J);
static SEXP meteoland_potentialRadiationSeries_try(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(potentialRadiationSeries(latrad, slorad, asprad, J));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_potentialRadiationSeries(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_potentialRadiationSeries_try(latradSEXP, sloradSEXP, aspradSEXP, JSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// potentialRadiationPoints
NumericVector potentialRadiationPoints(double latrad, NumericVector slorad, NumericVector asprad, int J);
static SEXP meteoland_potentialRadiationPoints_try(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(potentialRadiationPoints(latrad, slorad, asprad, J));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_potentialRadiationPoints(SEXP latradSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_potentialRadiationPoints_try(latradSEXP, sloradSEXP, aspradSEXP, JSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// radiationSeries
NumericVector radiationSeries(double latrad, double elevation, double slorad, double asprad, NumericVector J, NumericVector diffTemp, NumericVector diffTempMonth, NumericVector VP, NumericVector P);
static SEXP meteoland_radiationSeries_try(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP diffTempSEXP, SEXP diffTempMonthSEXP, SEXP VPSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type J(JSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diffTemp(diffTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diffTempMonth(diffTempMonthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VP(VPSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(radiationSeries(latrad, elevation, slorad, asprad, J, diffTemp, diffTempMonth, VP, P));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_radiationSeries(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP diffTempSEXP, SEXP diffTempMonthSEXP, SEXP VPSEXP, SEXP PSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_radiationSeries_try(latradSEXP, elevationSEXP, sloradSEXP, aspradSEXP, JSEXP, diffTempSEXP, diffTempMonthSEXP, VPSEXP, PSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// radiationPoints
NumericVector radiationPoints(NumericVector latrad, NumericVector elevation, NumericVector slorad, NumericVector asprad, int J, NumericVector diffTemp, NumericVector diffTempMonth, NumericVector VP, NumericVector P);
static SEXP meteoland_radiationPoints_try(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP diffTempSEXP, SEXP diffTempMonthSEXP, SEXP VPSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diffTemp(diffTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diffTempMonth(diffTempMonthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VP(VPSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(radiationPoints(latrad, elevation, slorad, asprad, J, diffTemp, diffTempMonth, VP, P));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_radiationPoints(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP diffTempSEXP, SEXP diffTempMonthSEXP, SEXP VPSEXP, SEXP PSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_radiationPoints_try(latradSEXP, elevationSEXP, sloradSEXP, aspradSEXP, JSEXP, diffTempSEXP, diffTempMonthSEXP, VPSEXP, PSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// meteo
DataFrame meteo(DataFrame MeteoMonth, NumericVector landscapeRainfall, double ERconv, double ERsyn, double shape, double scale, double albedo, int firstMonth, bool cyclic);
RcppExport SEXP meteoland_meteo(SEXP MeteoMonthSEXP, SEXP landscapeRainfallSEXP, SEXP ERconvSEXP, SEXP ERsynSEXP, SEXP shapeSEXP, SEXP scaleSEXP, SEXP albedoSEXP, SEXP firstMonthSEXP, SEXP cyclicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type MeteoMonth(MeteoMonthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type landscapeRainfall(landscapeRainfallSEXP);
    Rcpp::traits::input_parameter< double >::type ERconv(ERconvSEXP);
    Rcpp::traits::input_parameter< double >::type ERsyn(ERsynSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type albedo(albedoSEXP);
    Rcpp::traits::input_parameter< int >::type firstMonth(firstMonthSEXP);
    Rcpp::traits::input_parameter< bool >::type cyclic(cyclicSEXP);
    rcpp_result_gen = Rcpp::wrap(meteo(MeteoMonth, landscapeRainfall, ERconv, ERsyn, shape, scale, albedo, firstMonth, cyclic));
    return rcpp_result_gen;
END_RCPP
}
// vapourPressureFromRH
NumericMatrix vapourPressureFromRH(NumericMatrix T, NumericMatrix RH);
RcppExport SEXP meteoland_vapourPressureFromRH(SEXP TSEXP, SEXP RHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type RH(RHSEXP);
    rcpp_result_gen = Rcpp::wrap(vapourPressureFromRH(T, RH));
    return rcpp_result_gen;
END_RCPP
}
// dewpointTemperatureFromRH
NumericMatrix dewpointTemperatureFromRH(NumericMatrix T, NumericMatrix RH);
RcppExport SEXP meteoland_dewpointTemperatureFromRH(SEXP TSEXP, SEXP RHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type RH(RHSEXP);
    rcpp_result_gen = Rcpp::wrap(dewpointTemperatureFromRH(T, RH));
    return rcpp_result_gen;
END_RCPP
}
// temp2SVP
NumericVector temp2SVP(NumericVector TD);
RcppExport SEXP meteoland_temp2SVP(SEXP TDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type TD(TDSEXP);
    rcpp_result_gen = Rcpp::wrap(temp2SVP(TD));
    return rcpp_result_gen;
END_RCPP
}
// relativeHumidityFromMinMaxTemp
NumericVector relativeHumidityFromMinMaxTemp(NumericVector Tmin, NumericVector Tmax);
RcppExport SEXP meteoland_relativeHumidityFromMinMaxTemp(SEXP TminSEXP, SEXP TmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tmax(TmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(relativeHumidityFromMinMaxTemp(Tmin, Tmax));
    return rcpp_result_gen;
END_RCPP
}
// relativeHumidityFromDewpointTemp
NumericVector relativeHumidityFromDewpointTemp(NumericVector T, NumericVector TD);
RcppExport SEXP meteoland_relativeHumidityFromDewpointTemp(SEXP TSEXP, SEXP TDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TD(TDSEXP);
    rcpp_result_gen = Rcpp::wrap(relativeHumidityFromDewpointTemp(T, TD));
    return rcpp_result_gen;
END_RCPP
}
// interpolateTdewSeriesPoints
NumericMatrix interpolateTdewSeriesPoints(NumericVector Xp, NumericVector Yp, NumericVector Zp, NumericVector X, NumericVector Y, NumericVector Z, NumericMatrix T, double iniRp, double alpha, int N, int iterations);
RcppExport SEXP meteoland_interpolateTdewSeriesPoints(SEXP XpSEXP, SEXP YpSEXP, SEXP ZpSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP TSEXP, SEXP iniRpSEXP, SEXP alphaSEXP, SEXP NSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zp(ZpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type iniRp(iniRpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolateTdewSeriesPoints(Xp, Yp, Zp, X, Y, Z, T, iniRp, alpha, N, iterations));
    return rcpp_result_gen;
END_RCPP
}
// interpolateTemperatureSeriesPoints
NumericMatrix interpolateTemperatureSeriesPoints(NumericVector Xp, NumericVector Yp, NumericVector Zp, NumericVector X, NumericVector Y, NumericVector Z, NumericMatrix T, double iniRp, double alpha, int N, int iterations);
RcppExport SEXP meteoland_interpolateTemperatureSeriesPoints(SEXP XpSEXP, SEXP YpSEXP, SEXP ZpSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP TSEXP, SEXP iniRpSEXP, SEXP alphaSEXP, SEXP NSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zp(ZpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type iniRp(iniRpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolateTemperatureSeriesPoints(Xp, Yp, Zp, X, Y, Z, T, iniRp, alpha, N, iterations));
    return rcpp_result_gen;
END_RCPP
}
// saturationVapourPressure
double saturationVapourPressure(double temperature);
static SEXP meteoland_saturationVapourPressure_try(SEXP temperatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    rcpp_result_gen = Rcpp::wrap(saturationVapourPressure(temperature));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_saturationVapourPressure(SEXP temperatureSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_saturationVapourPressure_try(temperatureSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// averageDailyVapourPressure
double averageDailyVapourPressure(double Tmin, double Tmax, double RHmin, double RHmax);
static SEXP meteoland_averageDailyVapourPressure_try(SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< double >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< double >::type RHmin(RHminSEXP);
    Rcpp::traits::input_parameter< double >::type RHmax(RHmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(averageDailyVapourPressure(Tmin, Tmax, RHmin, RHmax));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_averageDailyVapourPressure(SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_averageDailyVapourPressure_try(TminSEXP, TmaxSEXP, RHminSEXP, RHmaxSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// atmosphericPressure
double atmosphericPressure(double elevation);
static SEXP meteoland_atmosphericPressure_try(SEXP elevationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    rcpp_result_gen = Rcpp::wrap(atmosphericPressure(elevation));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_atmosphericPressure(SEXP elevationSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_atmosphericPressure_try(elevationSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// airDensity
double airDensity(double temperature, double Patm);
static SEXP meteoland_airDensity_try(SEXP temperatureSEXP, SEXP PatmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type Patm(PatmSEXP);
    rcpp_result_gen = Rcpp::wrap(airDensity(temperature, Patm));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_airDensity(SEXP temperatureSEXP, SEXP PatmSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_airDensity_try(temperatureSEXP, PatmSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// averageDaylightTemperature
double averageDaylightTemperature(double Tmin, double Tmax);
static SEXP meteoland_averageDaylightTemperature_try(SEXP TminSEXP, SEXP TmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< double >::type Tmax(TmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(averageDaylightTemperature(Tmin, Tmax));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_averageDaylightTemperature(SEXP TminSEXP, SEXP TmaxSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_averageDaylightTemperature_try(TminSEXP, TmaxSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// latentHeatVaporisation
double latentHeatVaporisation(double temperature);
static SEXP meteoland_latentHeatVaporisation_try(SEXP temperatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    rcpp_result_gen = Rcpp::wrap(latentHeatVaporisation(temperature));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_latentHeatVaporisation(SEXP temperatureSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_latentHeatVaporisation_try(temperatureSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// latentHeatVaporisationMol
double latentHeatVaporisationMol(double temperature);
static SEXP meteoland_latentHeatVaporisationMol_try(SEXP temperatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    rcpp_result_gen = Rcpp::wrap(latentHeatVaporisationMol(temperature));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_latentHeatVaporisationMol(SEXP temperatureSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_latentHeatVaporisationMol_try(temperatureSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// psychrometricConstant
double psychrometricConstant(double temperature, double Patm);
static SEXP meteoland_psychrometricConstant_try(SEXP temperatureSEXP, SEXP PatmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type Patm(PatmSEXP);
    rcpp_result_gen = Rcpp::wrap(psychrometricConstant(temperature, Patm));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_psychrometricConstant(SEXP temperatureSEXP, SEXP PatmSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_psychrometricConstant_try(temperatureSEXP, PatmSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// saturationVaporPressureCurveSlope
double saturationVaporPressureCurveSlope(double temperature);
static SEXP meteoland_saturationVaporPressureCurveSlope_try(SEXP temperatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    rcpp_result_gen = Rcpp::wrap(saturationVaporPressureCurveSlope(temperature));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_saturationVaporPressureCurveSlope(SEXP temperatureSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_saturationVaporPressureCurveSlope_try(temperatureSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// PenmanPET
double PenmanPET(double latrad, double elevation, double slorad, double asprad, int J, double Tmin, double Tmax, double RHmin, double RHmax, double R_s, double u, double z, double z0, double alpha, String windfun);
static SEXP meteoland_PenmanPET_try(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP R_sSEXP, SEXP uSEXP, SEXP zSEXP, SEXP z0SEXP, SEXP alphaSEXP, SEXP windfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type latrad(latradSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type slorad(sloradSEXP);
    Rcpp::traits::input_parameter< double >::type asprad(aspradSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< double >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< double >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< double >::type RHmin(RHminSEXP);
    Rcpp::traits::input_parameter< double >::type RHmax(RHmaxSEXP);
    Rcpp::traits::input_parameter< double >::type R_s(R_sSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< String >::type windfun(windfunSEXP);
    rcpp_result_gen = Rcpp::wrap(PenmanPET(latrad, elevation, slorad, asprad, J, Tmin, Tmax, RHmin, RHmax, R_s, u, z, z0, alpha, windfun));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_PenmanPET(SEXP latradSEXP, SEXP elevationSEXP, SEXP sloradSEXP, SEXP aspradSEXP, SEXP JSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP R_sSEXP, SEXP uSEXP, SEXP zSEXP, SEXP z0SEXP, SEXP alphaSEXP, SEXP windfunSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_PenmanPET_try(latradSEXP, elevationSEXP, sloradSEXP, aspradSEXP, JSEXP, TminSEXP, TmaxSEXP, RHminSEXP, RHmaxSEXP, R_sSEXP, uSEXP, zSEXP, z0SEXP, alphaSEXP, windfunSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// PenmanMonteithPET
double PenmanMonteithPET(double rc, double elevation, double Tmin, double Tmax, double RHmin, double RHmax, double Rn, double u);
static SEXP meteoland_PenmanMonteithPET_try(SEXP rcSEXP, SEXP elevationSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP RnSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type rc(rcSEXP);
    Rcpp::traits::input_parameter< double >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< double >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< double >::type RHmin(RHminSEXP);
    Rcpp::traits::input_parameter< double >::type RHmax(RHmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Rn(RnSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(PenmanMonteithPET(rc, elevation, Tmin, Tmax, RHmin, RHmax, Rn, u));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP meteoland_PenmanMonteithPET(SEXP rcSEXP, SEXP elevationSEXP, SEXP TminSEXP, SEXP TmaxSEXP, SEXP RHminSEXP, SEXP RHmaxSEXP, SEXP RnSEXP, SEXP uSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(meteoland_PenmanMonteithPET_try(rcSEXP, elevationSEXP, TminSEXP, TmaxSEXP, RHminSEXP, RHmaxSEXP, RnSEXP, uSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// getWindFieldIndexAndFactor
List getWindFieldIndexAndFactor(NumericMatrix windSpeed, NumericMatrix windDirection, NumericMatrix wfSpeed, NumericMatrix wfDirection);
RcppExport SEXP meteoland_getWindFieldIndexAndFactor(SEXP windSpeedSEXP, SEXP windDirectionSEXP, SEXP wfSpeedSEXP, SEXP wfDirectionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type windSpeed(windSpeedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type windDirection(windDirectionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type wfSpeed(wfSpeedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type wfDirection(wfDirectionSEXP);
    rcpp_result_gen = Rcpp::wrap(getWindFieldIndexAndFactor(windSpeed, windDirection, wfSpeed, wfDirection));
    return rcpp_result_gen;
END_RCPP
}
// interpolateWindFieldSeriesPoints
List interpolateWindFieldSeriesPoints(NumericVector Xp, NumericVector Yp, NumericMatrix WS, NumericMatrix WD, NumericVector X, NumericVector Y, IntegerMatrix I, NumericMatrix F, double iniRp, double alpha, int N, int iterations);
RcppExport SEXP meteoland_interpolateWindFieldSeriesPoints(SEXP XpSEXP, SEXP YpSEXP, SEXP WSSEXP, SEXP WDSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ISEXP, SEXP FSEXP, SEXP iniRpSEXP, SEXP alphaSEXP, SEXP NSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WS(WSSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WD(WDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type I(ISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type F(FSEXP);
    Rcpp::traits::input_parameter< double >::type iniRp(iniRpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolateWindFieldSeriesPoints(Xp, Yp, WS, WD, X, Y, I, F, iniRp, alpha, N, iterations));
    return rcpp_result_gen;
END_RCPP
}
// interpolateWindStationSeriesPoints
List interpolateWindStationSeriesPoints(NumericVector Xp, NumericVector Yp, NumericMatrix WS, NumericMatrix WD, NumericVector X, NumericVector Y, double iniRp, double alpha, int N, int iterations);
RcppExport SEXP meteoland_interpolateWindStationSeriesPoints(SEXP XpSEXP, SEXP YpSEXP, SEXP WSSEXP, SEXP WDSEXP, SEXP XSEXP, SEXP YSEXP, SEXP iniRpSEXP, SEXP alphaSEXP, SEXP NSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WS(WSSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WD(WDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type iniRp(iniRpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolateWindStationSeriesPoints(Xp, Yp, WS, WD, X, Y, iniRp, alpha, N, iterations));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int meteoland_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("int(*radiation_julianDay)(int,int,int)");
        signatures.insert("IntegerVector(*radiation_dateStringToJulianDays)(CharacterVector)");
        signatures.insert("double(*radiation_solarDeclination)(int)");
        signatures.insert("double(*radiation_solarConstant)(int)");
        signatures.insert("NumericVector(*radiation_sunRiseSet)(double,double,double,double)");
        signatures.insert("double(*radiation_solarElevation)(double,double,double)");
        signatures.insert("double(*radiation_daylength)(double,double,double,double)");
        signatures.insert("double(*radiation_daylengthseconds)(double,double,double,double)");
        signatures.insert("double(*radiation_potentialRadiation)(double,double,double,double,double)");
        signatures.insert("double(*radiation_solarRadiation)(double,double,double,double,double,double,double,double,double,double)");
        signatures.insert("NumericVector(*radiation_directDiffuseInstant)(double,double,double,double,double,double,double,double,bool)");
        signatures.insert("DataFrame(*radiation_directDiffuseDay)(double,double,double,double,double,double,bool,int)");
        signatures.insert("double(*radiation_outgoingLongwaveRadiation)(double,double,double,double,double,double,double,double,double,double)");
        signatures.insert("double(*radiation_netRadiation)(double,double,double,double,double,double,double,double,double,double,double)");
        signatures.insert("NumericVector(*.potentialRadiationSeries)(double,double,double,NumericVector)");
        signatures.insert("NumericVector(*.potentialRadiationPoints)(double,NumericVector,NumericVector,int)");
        signatures.insert("NumericVector(*.radiationSeries)(double,double,double,double,NumericVector,NumericVector,NumericVector,NumericVector,NumericVector)");
        signatures.insert("NumericVector(*.radiationPoints)(NumericVector,NumericVector,NumericVector,NumericVector,int,NumericVector,NumericVector,NumericVector,NumericVector)");
        signatures.insert("double(*utils_saturationVP)(double)");
        signatures.insert("double(*utils_averageDailyVP)(double,double,double,double)");
        signatures.insert("double(*utils_atmosphericPressure)(double)");
        signatures.insert("double(*utils_airDensity)(double,double)");
        signatures.insert("double(*utils_averageDaylightTemperature)(double,double)");
        signatures.insert("double(*utils_latentHeatVaporisation)(double)");
        signatures.insert("double(*utils_latentHeatVaporisationMol)(double)");
        signatures.insert("double(*utils_psychrometricConstant)(double,double)");
        signatures.insert("double(*utils_saturationVaporPressureCurveSlope)(double)");
        signatures.insert("double(*penman)(double,double,double,double,int,double,double,double,double,double,double,double,double,double,String)");
        signatures.insert("double(*penmanmonteith)(double,double,double,double,double,double,double,double)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP meteoland_RcppExport_registerCCallable() { 
    R_RegisterCCallable("meteoland", "meteoland_radiation_julianDay", (DL_FUNC)meteoland_julianDay_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_dateStringToJulianDays", (DL_FUNC)meteoland_dateStringToJulianDays_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_solarDeclination", (DL_FUNC)meteoland_solarDeclination_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_solarConstant", (DL_FUNC)meteoland_solarConstant_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_sunRiseSet", (DL_FUNC)meteoland_sunRiseSet_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_solarElevation", (DL_FUNC)meteoland_solarElevation_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_daylength", (DL_FUNC)meteoland_daylength_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_daylengthseconds", (DL_FUNC)meteoland_daylengthseconds_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_potentialRadiation", (DL_FUNC)meteoland_RpotDay_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_solarRadiation", (DL_FUNC)meteoland_RDay_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_directDiffuseInstant", (DL_FUNC)meteoland_directDiffuseInstant_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_directDiffuseDay", (DL_FUNC)meteoland_directDiffuseDay_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_outgoingLongwaveRadiation", (DL_FUNC)meteoland_outgoingLongwaveRadiation_try);
    R_RegisterCCallable("meteoland", "meteoland_radiation_netRadiation", (DL_FUNC)meteoland_netRadiation_try);
    R_RegisterCCallable("meteoland", "meteoland_.potentialRadiationSeries", (DL_FUNC)meteoland_potentialRadiationSeries_try);
    R_RegisterCCallable("meteoland", "meteoland_.potentialRadiationPoints", (DL_FUNC)meteoland_potentialRadiationPoints_try);
    R_RegisterCCallable("meteoland", "meteoland_.radiationSeries", (DL_FUNC)meteoland_radiationSeries_try);
    R_RegisterCCallable("meteoland", "meteoland_.radiationPoints", (DL_FUNC)meteoland_radiationPoints_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_saturationVP", (DL_FUNC)meteoland_saturationVapourPressure_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_averageDailyVP", (DL_FUNC)meteoland_averageDailyVapourPressure_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_atmosphericPressure", (DL_FUNC)meteoland_atmosphericPressure_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_airDensity", (DL_FUNC)meteoland_airDensity_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_averageDaylightTemperature", (DL_FUNC)meteoland_averageDaylightTemperature_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_latentHeatVaporisation", (DL_FUNC)meteoland_latentHeatVaporisation_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_latentHeatVaporisationMol", (DL_FUNC)meteoland_latentHeatVaporisationMol_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_psychrometricConstant", (DL_FUNC)meteoland_psychrometricConstant_try);
    R_RegisterCCallable("meteoland", "meteoland_utils_saturationVaporPressureCurveSlope", (DL_FUNC)meteoland_saturationVaporPressureCurveSlope_try);
    R_RegisterCCallable("meteoland", "meteoland_penman", (DL_FUNC)meteoland_PenmanPET_try);
    R_RegisterCCallable("meteoland", "meteoland_penmanmonteith", (DL_FUNC)meteoland_PenmanMonteithPET_try);
    R_RegisterCCallable("meteoland", "meteoland_RcppExport_validate", (DL_FUNC)meteoland_RcppExport_validate);
    return R_NilValue;
}
