#' Fits Markov Chain Transition Matrices to State Sequence
#' Modified from weathergen
#' 
#' @param states character array of states (from {'d','w','e'}, for dry, wet and extremely wet)
#' @param months numeric array of months for each daily time step
#' @export
#' @return monthly list of transition matrices
#' @examples
#' transitions <- mc_fit(x=sample(c('d', 'w', 'e'), size=720, replace=TRUE, prob=c(0.5, 0.3, 0.2)), months=rep(rep(seq(1, 12), each=30), times=2))
#'
# 
.mc_fit<-function(states, months) {
  stopifnot(length(states) == length(months))
  ns <- 3
  s  <- c('d','w','e')
  states <- as.character(states)
  states_next <- c(states[2:length(states)],NA)
  transitions <- lapply(seq(1, 12), function(m) {
    idx <- which(months==m)
    t = matrix(0, 3,3,dimnames = list(s,s))
    for(i in 1:ns) for(j in 1:ns) t[i,j] = sum(states[idx]==s[i] & states_next[idx]==s[j], na.rm=T)
    t<-sweep(t, 1, rowSums(t, na.rm=T),"/")
    t[is.na(t)] <- 0
    t
  })
  transitions
}
#' Run Markov Chain Simulation
#'
#' @param months numeric array of months for each daily time step
#' @param initial initial state
#' @param transitions monthly list of transition matrices generated by mc_fit()
#' @param states character vector of markov states
#' @export
#' @examples
#' transitions <- mc_fit(x=sample(c('d', 'w', 'e'), size=720, replace=TRUE, prob=c(0.5, 0.3, 0.2)), 
#'                       months=rep(rep(seq(1, 12), each=30), times=2))
#' mc_simulate(months=rep(1:12, each=30), initial='d', transitions=transitions, states=c('d', 'w', 'e'))
#'
.mc_sim<-function(months, initial, transitions, states = c('d','w','e')) {
  n <- length(months)
  
  chain <- as.character(rep(NA, times=n))
  chain[1] <- initial
  
  for (i in 2:n) {
    chain[i] <- sample(states, size=1, prob=transitions[[months[i-1]]][chain[i-1], ])
  }
  return(chain)
}


#' Determine Markov State Thresholds from Precipitation
#'
#' @param x vector of daily precipitation
#' @param months vector of months corresponding to daily precipitation vector \code{x}
#' @param dry_wet_threshold threshold precipitation amount for dry/wet states
#' @param wet_extreme_quantile_threshold threshold quantile for wet/extreme states
#' @return monthly list of precipitation thresholds as vectors of length 2 
#' (first element is threshold amount between dry/wet, 
#' second element is threshold amount between wet/extreme)
.mc_state_threshold <- function(x, months, dry_wet_threshold=0.3, wet_extreme_quantile_threshold=0.8) {
  stopifnot(any(!is.na(x)))
  stopifnot(any(!is.na(months)))
  stopifnot(length(x) == length(months))
  
  thresh <- lapply(seq(1, 12), function(month) {
    idx <- which(months == month)
    if (length(idx) > 0) {
      x.month <- x[idx]
      res <- c(dry_wet=dry_wet_threshold, wet_extreme = max(dry_wet_threshold+0.1,
                                                       unname(quantile(x.month, probs=wet_extreme_quantile_threshold))))
    } else {
      res <- c(dry_wet=NA, wet_extreme=NA)
    }
    res
  })
  
  thresh
}

#' Assign Markov States from Precipitation and State Thresholds
#'
#' @param x vector of daily precipitation
#' @param months vector of months corresponding to daily precipitation
#' @param states character list of markov states
#' @param thresholds list of monthly transition matrices generated from mc_fit()
#' @export
.mc_assign_states <- function(x, months, thresholds) {
  stopifnot(length(x)==length(months))
  stopifnot(length(thresholds)==12)
  
  states <- c('d','w','e')
  state <- lapply(seq(1, 12), function(month) {
    idx <- which(months == month)
    if (length(idx) > 0) {
      x.month <- x[idx]
      res <- cut(x.month, breaks=c(0, thresholds[[month]], Inf), include.lowest=TRUE, right=TRUE, labels=states)
    } else {
      res <- character()
    }
    res
  })
  return(unlist(state))
}

weathergenerator<-function(x, params = defaultGenerationParams()) {
  months = as.numeric(format(as.Date(row.names(x)),"%m"))
  prec = x$Precipitation
  thresh <- .mc_state_threshold(prec, months, dry_wet_threshold = dry_wet_threshold, wet_extreme_quantile_threshold = wet_extreme_quantile_threshold)
  states <- .mc_assign_states(prec, months, thresh)
  transition <- .mc_fit(states, months)
  return(transition)
}